### ISSUE TITLE
Traceback (most recent call last):   File "run_oaisys.py", line 111, in <module>     SetupUtility.extract_file(blender_install_path, file_tmp, "TAR") NameError: name 'SetupUtility' is not defined

### ISSUE THREAD

**Issue by 1466758326** [DLR-RM/oaisys#12]
Traceback (most recent call last):
  File "run_oaisys.py", line 111, in <module>
    SetupUtility.extract_file(blender_install_path, file_tmp, "TAR")
NameError: name 'SetupUtility' is not defined
I am very interested in your work, but there are some problems when running the code, I would like to ask, what is the role of "SetupUtility" in the code

**Comment by mgmatDLR** [comment]
Thanks for the info. The issue should be resolved with the latest commit 06275c7.
