### ISSUE TITLE
Warning with specular texture

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [DLR-RM/oaisys#3]
When running the examples, I am getting the following warning
```
 WARNING: specular texture in folder /home/jaeyoung/dev/oaisys_external/src/assets/materials/../../../oaisys_data/examples/assets/materials/dry_ground_01/ cannot be found! Using default color!
```

Do I need to be concerned?

**Comment by mgmatDLR** [comment]
Is that the only warning you are getting?
If that's the case, you will be fine. OAISYS usually searches for either a roughness/reflectance or specular map. One of them should be provided to obtain the most realistic results, however they are not mandatory. If they are not provided OAISYS loads a solid default color map.

**Comment by Jaeyoung-Lim** [comment]
> Is that the only warning you are getting?

@mgmatDLR I think that is the case, thanks!
